codecov:
  token: 2d831214-3130-40e3-8b4b-31c86cd41ca7

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
